# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# cspell:ignore autofix shellcheck shfmt yamlfmt gitleaks unattend scrollback
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      # non-default
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: detect-private-key
      - id: mixed-line-ending
      - id: pretty-format-json
        args: ["--autofix"]
  - repo: https://github.com/google/yamlfmt
    rev: v0.11.0
    hooks:
      - id: yamlfmt
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.9.0
    hooks:
      - id: shellcheck
        args: ["--color=always", "--external-sources", "-e", "SC3020,SC3036"]
        types: ["executable", "file", "shell", "text"]
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.8.0-1
    hooks:
      - id: shfmt
        args:
          - "--diff"
          - "--indent"
          - "4"
          - "--binary-next-line"
          #- "--space-redirects"
          - "--case-indent"
          - "-ln"
          - "bash"
        types: ["executable", "file", "shell", "text"]
        exclude: |
          (?x)^(
              SCRIPTS_ARCHIVE/.*|
              path/to/file\.py
          )$
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.2
    hooks:
      - id: gitleaks
        args: ["--no-banner"]
  - repo: https://github.com/amperser/proselint
    rev: 0.13.0
    hooks:
      - id: proselint
        #types: ["asciidoc", "file", "non-executable", "plain-text", "text"]
        #types: ["asciidoc", "markdown", "file", "non-executable", "text"]
        types: ["text", "non-executable"]
        #additional_dependencies: [proselint]
        exclude: |
          (?x)^(
              scripts/update-tailscale/notes_install.adoc|
              path/to/file\.py
          )$
